name: YouTube Crawler

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      max_videos:
        description: 'Max videos per keyword'
        required: false
        default: '400'

  # Scheduled runs (daily at 3 AM UTC)
  schedule:
    - cron: '0 3 * * *'

jobs:
  crawl-youtube:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run YouTube Crawler
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          YOUTUBE_API_KEYS: ${{ secrets.YOUTUBE_API_KEYS }}
          YOUTUBE_KEYWORDS: ${{ secrets.YOUTUBE_KEYWORDS }}
          YOUTUBE_MAX_VIDEOS_PER_KEYWORD: ${{ github.event.inputs.max_videos || '400' }}
          LOG_LEVEL: INFO
        run: |
          python -m src.main youtube

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: youtube-logs-${{ github.run_number }}
          path: logs/
          retention-days: 7

      - name: Upload data
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: youtube-data-${{ github.run_number }}
          path: data/
          retention-days: 7

      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ YouTube crawler failed!"
          echo "Check logs for details."