name: Facebook Crawler

on:
  # Manual trigger
  workflow_dispatch:
    inputs:
      max_scrolls:
        description: 'Number of scrolls'
        required: false
        default: '5'

  # Scheduled runs (every 6 hours)
  schedule:
    - cron: '0 */6 * * *' # At 0:00, 6:00, 12:00, 18:00 UTC

jobs:
  crawl-facebook:
    # ❌ THAY ĐỔI 1: CHUYỂN SANG SELF-HOSTED RUNNER CỦA BẠN
    # Sử dụng nhãn 'self-hosted' (và nhãn 'linux', 'X64' để nhắm mục tiêu chính xác hơn)
    runs-on: [self-hosted, linux, X64] 
    timeout-minutes: 45

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # ❌ THAY ĐỔI 2: PLAYWRIGHT INSTALL (KHÔNG CẦN CHẠY LẠI INSTALL-DEPS)
      # Trên self-hosted runner, các dependency hệ thống đã được cài đặt thủ công. 
      # Chỉ cần cài đặt trình duyệt (binaries).
      - name: Install Playwright browsers
        # Sử dụng python -m để đảm bảo bạn dùng Playwright đã cài đặt cho phiên bản Python đó
        run: |
          python -m playwright install chromium
          
      # Lưu ý: Các thư viện hệ thống (install-deps) cho Playwright đã được cài đặt 
      # thủ công trên EC2, do đó không cần chạy lại 'playwright install-deps chromium' 
      # trong workflow này nữa.

      # ... (Các bước còn lại giữ nguyên) ...

      - name: Run Facebook Crawler
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_DB: ${{ secrets.FACEBOOK_DB }}
          FACEBOOK_COOKIE: ${{ secrets.FACEBOOK_COOKIE }}
          FACEBOOK_KEYWORDS: ${{ secrets.FACEBOOK_KEYWORDS }}
          MAX_SCROLLS: ${{ github.event.inputs.max_scrolls || '5' }}
          LOG_LEVEL: INFO
          # PLAYWRIGHT_BROWSERS_PATH: /ms-playwright - KHÔNG CẦN THIẾT
          # Bỏ dòng này vì trên Linux, Playwright sẽ tự tìm trong thư mục người dùng (user directory) 
          # sau khi chạy 'python -m playwright install chromium'
        run: |
          python -m src.main facebook
          
      # ... (Các bước Upload và Kiểm tra kết quả giữ nguyên) ...
